version: 2
jobs:

  build-npm:
    docker:
    - image: circleci/node:9

    steps:
    - checkout
  
    - run: npm install
    - run: rpm run scss


  build-php:
    docker:
    - image: circleci/php:7.1-apache-stretch-browsers

    steps:
    - checkout

    - restore_cache:
        keys:
        - v2-php-vendor-{{ checksum "composer.lock" }}
        - v2-php-vendor-

    - run: composer install

    - save_cache:   
        key: v2-php-vendor-{{ checksum "composer.lock" }}
        paths:
        - vendor

    - restore_cache:
        keys:
        - v1-code-standards-{{ BRANCH_NAME }} 
        - v1-code-standards-master

    - run: vendor/bin/php-cs-fixer fix --dry-run --verbose

    - save_cache:
        key: v1-code-standards-{{ BRANCH_NAME }} 
        paths: cs/cache


    - run: vendor/bin/phpunit
    - run: composer validate --strict
    - run: vendor/bin/parallel-lint src tests
    - run: vendor/bin/security-checker security:check



workflows:
  version: 2
  build:
    jobs:
    - build-npm
    - build-php

