version: 2
jobs:

  build-npm:
    docker:
    - image: circleci/node:9

    steps:
    - checkout
  
    - restore_cache:
        keys:
        - v2-npm-{{ checksum "package-lock.json" }}
        - v2-npm-

    - run: npm install

    - save_cache:   
        key: v2-npm-{{ checksum "package-lock.json" }}
        paths:
        - node_modules


    - run: npm run scss


  build-php:
    docker:
    - image: circleci/php:7.1-apache-stretch-browsers

    steps:
    - checkout

    - restore_cache:
        keys:
        - v2-php-vendor-{{ checksum "composer.lock" }}
        - v2-php-vendor-

    - run: composer install

    - save_cache:   
        key: v2-php-vendor-{{ checksum "composer.lock" }}
        paths:
        - vendor


    - run: cat css/demo.css
    - run: vendor/bin/phpunit
    - run: composer validate --strict
    - run: vendor/bin/php-cs-fixer fix --dry-run --verbose
    - run: vendor/bin/parallel-lint src tests
    - run: vendor/bin/security-checker security:check



workflows:
  version: 2
  build:
    jobs:
    - build-npm
    - build-php

